# Generated by Django 5.1.7 on 2025-03-21 10:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TideLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TideData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("high", models.BooleanField()),
                ("height", models.DecimalField(decimal_places=3, max_digits=6)),
                ("occurs", models.DateTimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tides.tidelocation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["location", "occurs"],
                        name="tides_tided_locatio_1d4d9a_idx",
                    )
                ],
            },
        ),
    ]
