name: Run Check Code

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Update apt database
        run: |
          sudo apt update
      - name: Install apt depends
        run: |
          sudo apt install -y gdal-bin libgdal-dev
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Setup venv
        run: |
          ./setup.sh
      - name: check-code
        run: |
          ./check-code.sh
